const laptops = [
  {
    "index": 1,
    "brand": "tecno",
    "Model": "Tecno Megabook T1 Laptop (11th Gen Core i3/ 8GB/ 512GB SSD/ Win11 Home)",
    "Price": 23990,
    "Rating": 63,
    "processor_brand": "intel",
    "processor_tier": "core i3",
    "num_cores": 2,
    "num_threads": 4,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 2,
    "brand": "tecno",
    "Model": "Tecno Megabook T1 Laptop (11th Gen Core i7/ 16GB/ 1TB SSD/ Win11 Home)",
    "Price": 35990,
    "Rating": 67,
    "processor_brand": "intel",
    "processor_tier": "core i7",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 3,
    "brand": "hp",
    "Model": "HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen 5 5600H/ 8GB/ 512GB SSD/ Win11/ 4GB Graph)",
    "Price": 51100,
    "Rating": 73,
    "processor_brand": "amd",
    "processor_tier": "ryzen 5",
    "num_cores": 6,
    "num_threads": 12,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "amd",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 4,
    "brand": "acer",
    "Model": "Acer Extensa EX214-53 Laptop (12th Gen Core i5/ 8GB/ 512GB SSD/ Win11 Home)",
    "Price": 39990,
    "Rating": 62,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 12,
    "num_threads": 16,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 14.0,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 5,
    "brand": "lenovo",
    "Model": "Lenovo V15 82KDA01BIH Laptop (AMD Ryzen 3 5300U/ 8GB/ 512GB SSD/ Win11 Home)",
    "Price": 28580,
    "Rating": 62,
    "processor_brand": "amd",
    "processor_tier": "ryzen 3",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "amd",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 6,
    "brand": "apple",
    "Model": "Apple MacBook Air 2020 MGND3HN Laptop (Apple M1/ 8GB/ 256GB SSD/ MacOS)",
    "Price": 70990,
    "Rating": 45,
    "processor_brand": "apple",
    "processor_tier": "m1",
    "num_cores": 8,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 256,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "apple",
    "gpu_type": "apple",
    "is_touch_screen": false,
    "display_size": 13.3,
    "resolution_width": 2560,
    "resolution_height": 1600,
    "OS": "mac",
    "year_of_warranty": "1"
  },
  {
    "index": 7,
    "brand": "infinix",
    "Model": "Infinix INBook Y2 Plus Laptop (11th Gen Core i5/ 16GB/ 512GB SSD/ Win 11 Home)",
    "Price": 34990,
    "Rating": 56,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 8,
    "brand": "asus",
    "Model": "Asus TUF Gaming F15 FX506HF-HN024W Gaming Laptop (11th Gen Core i5/ 8GB/ 512GB SSD/ Win11/ 4GB Graph)",
    "Price": 49990,
    "Rating": 70,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 6,
    "num_threads": 12,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 9,
    "brand": "hp",
    "Model": "HP 15s-fq5007TU Laptop (12th Gen Core i3/ 8GB/ 512GB SSD/ Win11 Home)",
    "Price": 36990,
    "Rating": 60,
    "processor_brand": "intel",
    "processor_tier": "core i3",
    "num_cores": 6,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 10,
    "brand": "infinix",
    "Model": "Infinix Zerobook 2023 Laptop (13th Gen Core i9/ 32GB/ 1TB SSD/ Win 11 Home)",
    "Price": 59990,
    "Rating": 71,
    "processor_brand": "intel",
    "processor_tier": "core i9",
    "num_cores": 14,
    "num_threads": 20,
    "ram_memory": 32,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 11,
    "brand": "dell",
    "Model": "Dell Inspiron 3520 D560896WIN9B Laptop (12th Gen Core i3/ 8GB/ 512GB SSD/ Win11)",
    "Price": 34990,
    "Rating": 60,
    "processor_brand": "intel",
    "processor_tier": "core i3",
    "num_cores": 6,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 12,
    "brand": "samsung",
    "Model": "Samsung Galaxy Book2 Pro 13 Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11)",
    "Price": 64990,
    "Rating": 68,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 12,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 13.3,
    "resolution_width": 1080,
    "resolution_height": 1920,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 13,
    "brand": "msi",
    "Model": "MSI Thin GF63 12UC-846IN Gaming Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home/ 4GB Graphics)",
    "Price": 52990,
    "Rating": 71,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 8,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "2"
  },
  {
    "index": 14,
    "brand": "asus",
    "Model": "Asus Vivobook 16X 2022 M1603QA-MB711WS Laptop (Ryzen 7-5800H/ 16GB/ 512GB SSD/ Win11 Home)",
    "Price": 57390,
    "Rating": 71,
    "processor_brand": "amd",
    "processor_tier": "ryzen 7",
    "num_cores": 8,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "amd",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 16.0,
    "resolution_width": 1920,
    "resolution_height": 1200,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 15,
    "brand": "lenovo",
    "Model": "Lenovo IdeaPad Slim 3 82H803LKIN Laptop (11th Gen Core i5/ 16GB/ 512GB SSD/ Win11)",
    "Price": 47490,
    "Rating": 66,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 16,
    "brand": "hp",
    "Model": "HP Omen 16-wf1025TX Gaming Laptop (14th Gen Core i7/ 16GB/ 1TB SSD/ Win11 Home/ 8GB Graph)",
    "Price": 153990,
    "Rating": 85,
    "processor_brand": "intel",
    "processor_tier": "core i7",
    "num_cores": 20,
    "num_threads": 28,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 16.1,
    "resolution_width": 2560,
    "resolution_height": 1440,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 17,
    "brand": "lenovo",
    "Model": "Lenovo V15 G3 IAP 82TTA08AIN Laptop (12th Gen Core i7/ 16GB/ 512GB SSD/Win11)",
    "Price": 49990,
    "Rating": 59,
    "processor_brand": "intel",
    "processor_tier": "core i7",
    "num_cores": 10,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 18,
    "brand": "asus",
    "Model": "Asus TUF Gaming F15 FX506HE-HN385WS Gaming Laptop (11th Gen Core i7/ 16GB/ 1TB SSD/ Win11/ 4GB Graph)",
    "Price": 75990,
    "Rating": 76,
    "processor_brand": "intel",
    "processor_tier": "core i7",
    "num_cores": 8,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 19,
    "brand": "hp",
    "Model": "HP Victus 15-fb1017AX Gaming Laptop (AMD Ryzen 5 7535HS/ 16GB/ 512GB SSD/ Win11/ 4GB Graph)",
    "Price": 55490,
    "Rating": 71,
    "processor_brand": "amd",
    "processor_tier": "ryzen 5",
    "num_cores": 6,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 20,
    "brand": "wings",
    "Model": "Wings Nuvobook V1 Laptop (11th Gen Core i5/ 8GB/ 512GB SSD/ Win11)",
    "Price": 27990,
    "Rating": 56,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1080,
    "resolution_height": 1920,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 21,
    "brand": "hp",
    "Model": "HP 255 G9 840T7PA Laptop (AMD Athlon Silver-3050U/ 4GB/ 256GB SSD/ DOS)",
    "Price": 19299,
    "Rating": 49,
    "processor_brand": "amd",
    "processor_tier": "other",
    "num_cores": 2,
    "num_threads": 2,
    "ram_memory": 4,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 256,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "amd",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1366,
    "resolution_height": 768,
    "OS": "dos",
    "year_of_warranty": "1"
  },
  {
    "index": 22,
    "brand": "lenovo",
    "Model": "Lenovo V15 G4 82YU00W7IN Laptop (AMD Ryzen 3 7320U/ 8GB/ 512GB SSD/ Win11 Home)",
    "Price": 27990,
    "Rating": 59,
    "processor_brand": "amd",
    "processor_tier": "ryzen 3",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "amd",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 23,
    "brand": "apple",
    "Model": "Apple MacBook Pro 16 2023 Laptop (Apple M3 Max/ 48GB/ 1TB SSD/ macOS)",
    "Price": 399900,
    "Rating": 65,
    "processor_brand": "apple",
    "processor_tier": "m3",
    "num_cores": 16,
    "num_threads": 16,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "apple",
    "gpu_type": "apple",
    "is_touch_screen": false,
    "display_size": 16.2,
    "resolution_width": 3456,
    "resolution_height": 2234,
    "OS": "mac",
    "year_of_warranty": "1"
  },
  {
    "index": 24,
    "brand": "asus",
    "Model": "Asus Vivobook 15 X1502ZA-EJ385WS Laptop (12th Gen Core i3/ 8GB/ 512GB SSD/ Win11)",
    "Price": 39990,
    "Rating": 57,
    "processor_brand": "intel",
    "processor_tier": "core i3",
    "num_cores": 10,
    "num_threads": 12,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 25,
    "brand": "asus",
    "Model": "Asus VivoBook 15 X1500EA-EJ311W Laptop (11th Gen Core i3/ 8GB/ 256GB SSD/ Win11)",
    "Price": 27990,
    "Rating": 57,
    "processor_brand": "intel",
    "processor_tier": "core i3",
    "num_cores": 2,
    "num_threads": 4,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 256,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 26,
    "brand": "acer",
    "Model": "Acer Nitro V ANV15-51 2023 Gaming Laptop (13th Gen Core i5/ 16GB/ 512GB SSD/ Win11/ 6GB Graph)",
    "Price": 77990,
    "Rating": 63,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 8,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 27,
    "brand": "hp",
    "Model": "HP Victus 16-s0094AX Gaming Laptop (AMD Ryzen 7 7840HS/ 16GB/ 1TB SSD/ Win11/ 6GB Graph)",
    "Price": 78990,
    "Rating": 77,
    "processor_brand": "amd",
    "processor_tier": "ryzen 7",
    "num_cores": 8,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 16.1,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 28,
    "brand": "ultimus",
    "Model": "Ultimus Elite NU14U3INF56BN-CS Laptop (10th Gen Core i5 / 8GB/ 512GB SSD/ Win11 Home)",
    "Price": 19990,
    "Rating": 54,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 14.1,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 30,
    "brand": "hp",
    "Model": "HP Pavilion 15-eg3081TU Laptop (13th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home)",
    "Price": 71999,
    "Rating": 66,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 12,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 31,
    "brand": "msi",
    "Model": "MSI GF63 Thin 11UC-1294IN Gaming Laptop (11th Gen Core i7/ 16GB/ 1TB 256GB SSD/ Win11/ 4GB Graph)",
    "Price": 66780,
    "Rating": 76,
    "processor_brand": "intel",
    "processor_tier": "core i7",
    "num_cores": 8,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "HDD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "SSD",
    "secondary_storage_capacity": 256,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "No information"
  },
  {
    "index": 32,
    "brand": "samsung",
    "Model": "Samsung Galaxy Book2 NP550XED-KA1IN 15 Laptop (12th Gen Core i5/ 8GB/ 512GB SSD/ Win11)",
    "Price": 44990,
    "Rating": 59,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 10,
    "num_threads": 12,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 33,
    "brand": "samsung",
    "Model": "Samsung Galaxy Book2 NP550XED-KA2IN Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11)",
    "Price": 47990,
    "Rating": 62,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 10,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 34,
    "brand": "lenovo",
    "Model": "Lenovo IdeaPad Gaming 3 15IHU6 82K101GSIN Laptop (11th Gen Core i5/ 8GB/ 512GB SSD/ Win11 Home/ 4GB Graph)",
    "Price": 47990,
    "Rating": 71,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 35,
    "brand": "asus",
    "Model": "Asus Vivobook 16X 2022 M1603QA-MB502WS Laptop (Ryzen 5-5600H/ 8GB/ 512GB SSD/ Win11 Home)",
    "Price": 46990,
    "Rating": 65,
    "processor_brand": "amd",
    "processor_tier": "ryzen 5",
    "num_cores": 6,
    "num_threads": 12,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "amd",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 16.0,
    "resolution_width": 1920,
    "resolution_height": 1200,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 36,
    "brand": "apple",
    "Model": "Apple MacBook Air 2022 Laptop (Apple M2/ 8GB/ 256GB SSD/ MacOS)",
    "Price": 102990,
    "Rating": 48,
    "processor_brand": "apple",
    "processor_tier": "m2",
    "num_cores": 8,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 256,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "apple",
    "gpu_type": "apple",
    "is_touch_screen": false,
    "display_size": 13.6,
    "resolution_width": 2560,
    "resolution_height": 1664,
    "OS": "mac",
    "year_of_warranty": "1"
  },
  {
    "index": 37,
    "brand": "dell",
    "Model": "Dell G15-5520 Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home/ 4GB Graph)",
    "Price": 68239,
    "Rating": 66,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 12,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 38,
    "brand": "acer",
    "Model": "Acer Aspire Lite AL15-52 15 Laptop (12th Gen Core i5/ 16GB/ 1TB SSD/ Win11)",
    "Price": 46990,
    "Rating": 64,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 10,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 39,
    "brand": "acer",
    "Model": "Acer Aspire Lite 15 AL15-52 Laptop (12th Gen Core i3/ 16GB/ 512GB SSD/ Win11)",
    "Price": 34990,
    "Rating": 60,
    "processor_brand": "intel",
    "processor_tier": "core i3",
    "num_cores": 6,
    "num_threads": 8,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 40,
    "brand": "hp",
    "Model": "HP 15s-fr5011TU Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home)",
    "Price": 53990,
    "Rating": 62,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 10,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 41,
    "brand": "asus",
    "Model": "Asus Vivobook 16X 2023 K3605ZF-MB541WS Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home/ 4GB Graph)",
    "Price": 63990,
    "Rating": 72,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 8,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 16.0,
    "resolution_width": 1920,
    "resolution_height": 1200,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 42,
    "brand": "asus",
    "Model": "Asus ROG Flow X13 GV301RC-LJ132WS Gaming Laptop (AMD Ryzen 9 6900HS/ 16GB/ 512GB SSD/ Win11 Home/ 4GB Graph)",
    "Price": 113571,
    "Rating": 77,
    "processor_brand": "amd",
    "processor_tier": "ryzen 9",
    "num_cores": 8,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": true,
    "display_size": 13.4,
    "resolution_width": 1920,
    "resolution_height": 1200,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 43,
    "brand": "hp",
    "Model": "HP Victus 15-fa1062TX Gaming Laptop (13th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home/ 6GB Graph)",
    "Price": 88800,
    "Rating": 71,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 12,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 45,
    "brand": "hp",
    "Model": "HP Victus 15-fb0150AX Gaming Laptop (AMD Ryzen 5 5600H/ 16GB/ 512GB SSD/ Win11/ 4GB Graph)",
    "Price": 53570,
    "Rating": 71,
    "processor_brand": "amd",
    "processor_tier": "ryzen 5",
    "num_cores": 6,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "amd",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 46,
    "brand": "hp",
    "Model": "HP Omen 16-xf0060AX Gaming Laptop (AMD Ryzen 7 7840HS/ 16GB/ 1TB SSD/ Win11/ 8GB Graph)",
    "Price": 116990,
    "Rating": 80,
    "processor_brand": "amd",
    "processor_tier": "ryzen 7",
    "num_cores": 8,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 16.0,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 47,
    "brand": "hp",
    "Model": "HP Victus 15-fa0555TX  Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home/ 4GB Graph)",
    "Price": 70810,
    "Rating": 71,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 8,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 48,
    "brand": "dell",
    "Model": "Dell G15-5530 GN5530D83M6002ORB1 Gaming Laptop (13th Gen Core i5/ 16GB/ 512GB SSD/ Win11/ 6GB Graph)",
    "Price": 81290,
    "Rating": 71,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 10,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 49,
    "brand": "msi",
    "Model": "MSI Modern 14 C11M-030IN Laptop (11th Gen Core i5/ 8GB/ 512GB SSD/ Win11 Home)",
    "Price": 35950,
    "Rating": 58,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 14.0,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 50,
    "brand": "asus",
    "Model": "Asus ROG Strix SCAR 16 2023 G634JZ-NM057WS Gaming Laptop (13th Gen Core i9/ 32GB/ 1TB SSD/ Win11 Home/ 12GB Graph)",
    "Price": 269990,
    "Rating": 83,
    "processor_brand": "intel",
    "processor_tier": "core i9",
    "num_cores": 24,
    "num_threads": 32,
    "ram_memory": 32,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 1024,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 16.0,
    "resolution_width": 2560,
    "resolution_height": 1600,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 51,
    "brand": "msi",
    "Model": "MSI Thin GF63 12VE-071IN Gaming Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home/6GB Graphics)",
    "Price": 69990,
    "Rating": 70,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 8,
    "num_threads": 12,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "2"
  },
  {
    "index": 53,
    "brand": "dell",
    "Model": "Dell Vostro 3425 Laptop (AMD Ryzen 5 5625U/ 8GB/ 512GB SSD/ Win11 Home)",
    "Price": 39649,
    "Rating": 66,
    "processor_brand": "amd",
    "processor_tier": "ryzen 5",
    "num_cores": 6,
    "num_threads": 12,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "amd",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 14.0,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 56,
    "brand": "infinix",
    "Model": "Infinix INBook Y1 Plus 15 XL28 Laptop (10th Gen Core i5/ 8GB/ 512GB SSD/ Win 11 Home)",
    "Price": 29990,
    "Rating": 54,
    "processor_brand": "intel",
    "processor_tier": "core i5",
    "num_cores": 4,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 57,
    "brand": "acer",
    "Model": "Acer Aspire Lite AL15-52 Laptop (12th Gen Core i3/ 8GB/ 512GB SSD/ Win11)",
    "Price": 32990,
    "Rating": 58,
    "processor_brand": "intel",
    "processor_tier": "core i3",
    "num_cores": 6,
    "num_threads": 8,
    "ram_memory": 8,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "intel",
    "gpu_type": "integrated",
    "is_touch_screen": false,
    "display_size": 15.6,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  },
  {
    "index": 58,
    "brand": "hp",
    "Model": "HP Victus 16-s0095AX Gaming Laptop (AMD Ryzen 7 7840HS/ 16GB/ 512GB SSD/ Win11/ 6GB Graph)",
    "Price": 83590,
    "Rating": 76,
    "processor_brand": "amd",
    "processor_tier": "ryzen 7",
    "num_cores": 8,
    "num_threads": 16,
    "ram_memory": 16,
    "primary_storage_type": "SSD",
    "primary_storage_capacity": 512,
    "secondary_storage_type": "No secondary storage",
    "secondary_storage_capacity": 0,
    "gpu_brand": "nvidia",
    "gpu_type": "dedicated",
    "is_touch_screen": false,
    "display_size": 16.1,
    "resolution_width": 1920,
    "resolution_height": 1080,
    "OS": "windows",
    "year_of_warranty": "1"
  }]
module.exports = laptops;