module.exports = [
  {
    "brand": "oneplus",
    "model": "OnePlus 11 5G",
    "price": 54999,
    "rating": 89,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 3.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 100,
    "ramCapacity": 12,
    "internalMemory": 256,
    "screenSize": 6.7,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1440,
      "height": 3216
    },
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.in%2FApple-iPhone-15-Plus-128%2Fdp%2FB0CHX6X2WW&psig=AOvVaw0fbRq9wGEhBY2K5rBh9t4Z&ust=1752387907487000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJDSrOfXto4DFQAAAAAdAAAAABAE"
  },
  {
    "brand": "oneplus",
    "model": "OnePlus Nord CE 2 Lite 5G",
    "price": 19989,
    "rating": 81,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 33,
    "ramCapacity": 6,
    "internalMemory": 128,
    "screenSize": 6.59,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 64,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2412
    },
    "image": ""
  },
  {
    "brand": "samsung",
    "model": "Samsung Galaxy A14 5G",
    "price": 16499,
    "rating": 75,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "exynos",
    "numCores": 8,
    "processorSpeed": 2.4,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 15,
    "ramCapacity": 4,
    "internalMemory": 64,
    "screenSize": 6.6,
    "refreshRate": 90,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 13,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2408
    },
    "image": ""
  },
  {
    "brand": "motorola",
    "model": "Motorola Moto G62 5G",
    "price": 14999,
    "rating": 81,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 0,
    "ramCapacity": 6,
    "internalMemory": 128,
    "screenSize": 6.55,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "realme",
    "model": "Realme 10 Pro Plus",
    "price": 24999,
    "rating": 82,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "dimensity",
    "numCores": 8,
    "processorSpeed": 2.6,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 67,
    "ramCapacity": 6,
    "internalMemory": 128,
    "screenSize": 6.7,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 108,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2412
    },
    "image": ""
  },
  {
    "brand": "samsung",
    "model": "Samsung Galaxy F23 5G (6GB RAM + 128GB)",
    "price": 16999,
    "rating": 80,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 25,
    "ramCapacity": 6,
    "internalMemory": 128,
    "screenSize": 6.6,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 8,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2408
    },
    "image": ""
  },
  {
    "brand": "apple",
    "model": "Apple iPhone 14",
    "price": 65999,
    "rating": 81,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "bionic",
    "numCores": 6,
    "processorSpeed": 3.22,
    "batteryCapacity": 3279,
    "fastChargingAvailable": true,
    "fastCharging": 0,
    "ramCapacity": 6,
    "internalMemory": 128,
    "screenSize": 6.1,
    "refreshRate": 60,
    "numRearCameras": 2,
    "numFrontCameras": 1,
    "os": "ios",
    "primaryCameraRear": 12,
    "primaryCameraFront": 12,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1170,
      "height": 2532
    },
    "image": ""
  },
  {
    "brand": "xiaomi",
    "model": "Xiaomi Redmi Note 12 Pro Plus",
    "price": 29999,
    "rating": 86,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": true,
    "processorBrand": "dimensity",
    "numCores": 8,
    "processorSpeed": 2.6,
    "batteryCapacity": 4980,
    "fastChargingAvailable": true,
    "fastCharging": 120,
    "ramCapacity": 8,
    "internalMemory": 256,
    "screenSize": 6.67,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 200,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "nothing",
    "model": "Nothing Phone 1",
    "price": 26749,
    "rating": 85,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.5,
    "batteryCapacity": 4500,
    "fastChargingAvailable": true,
    "fastCharging": 33,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.55,
    "refreshRate": 120,
    "numRearCameras": 2,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "oneplus",
    "model": "OnePlus Nord 2T 5G",
    "price": 28999,
    "rating": 84,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "dimensity",
    "numCores": 8,
    "processorSpeed": 3.0,
    "batteryCapacity": 4500,
    "fastChargingAvailable": true,
    "fastCharging": 80,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.43,
    "refreshRate": 90,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 32,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "realme",
    "model": "Realme 10 Pro",
    "price": 18999,
    "rating": 82,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 33,
    "ramCapacity": 6,
    "internalMemory": 128,
    "screenSize": 6.72,
    "refreshRate": 120,
    "numRearCameras": 2,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 108,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "oppo",
    "model": "Oppo A78",
    "price": 18999,
    "rating": 79,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "dimensity",
    "numCores": 8,
    "processorSpeed": 2.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 33,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.56,
    "refreshRate": 90,
    "numRearCameras": 2,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 8,
    "extendedMemoryAvailable": true,
    "extendedUpto": 0,
    "resolution": {
      "width": 720,
      "height": 1612
    },
    "image": ""
  },
  {
    "brand": "xiaomi",
    "model": "Xiaomi Redmi Note 12 Pro 5G",
    "price": 24762,
    "rating": 79,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": true,
    "processorBrand": "dimensity",
    "numCores": 8,
    "processorSpeed": 2.6,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 67,
    "ramCapacity": 6,
    "internalMemory": 128,
    "screenSize": 6.67,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "vivo",
    "model": "Vivo T1 5G (6GB RAM + 128GB)",
    "price": 16990,
    "rating": 80,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 18,
    "ramCapacity": 6,
    "internalMemory": 128,
    "screenSize": 6.58,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2408
    },
    "image": ""
  },
  {
    "brand": "samsung",
    "model": "Samsung Galaxy S23 Ultra 5G",
    "price": 114990,
    "rating": 0,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 3.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 45,
    "ramCapacity": 8,
    "internalMemory": 256,
    "screenSize": 6.8,
    "refreshRate": 120,
    "numRearCameras": 4,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 200,
    "primaryCameraFront": 12,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1440,
      "height": 3088
    },
    "image": ""
  },
  {
    "brand": "apple",
    "model": "Apple iPhone 13",
    "price": 62999,
    "rating": 79,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "bionic",
    "numCores": 6,
    "processorSpeed": 3.22,
    "batteryCapacity": 3240,
    "fastChargingAvailable": true,
    "fastCharging": 0,
    "ramCapacity": 4,
    "internalMemory": 128,
    "screenSize": 6.1,
    "refreshRate": 60,
    "numRearCameras": 2,
    "numFrontCameras": 1,
    "os": "ios",
    "primaryCameraRear": 12,
    "primaryCameraFront": 12,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1170,
      "height": 2532
    },
    "image": ""
  },
  {
    "brand": "vivo",
    "model": "Vivo Y16",
    "price": 9999,
    "rating": 65,
    "has5g": false,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "helio",
    "numCores": 8,
    "processorSpeed": 2.3,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 10,
    "ramCapacity": 3,
    "internalMemory": 32,
    "screenSize": 6.51,
    "refreshRate": 60,
    "numRearCameras": 2,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 13,
    "primaryCameraFront": 5,
    "extendedMemoryAvailable": true,
    "extendedUpto": 0,
    "resolution": {
      "width": 720,
      "height": 1600
    },
    "image": ""
  },
  {
    "brand": "oppo",
    "model": "OPPO Reno 9 Pro Plus",
    "price": 45999,
    "rating": 86,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 3.2,
    "batteryCapacity": 4700,
    "fastChargingAvailable": true,
    "fastCharging": 80,
    "ramCapacity": 16,
    "internalMemory": 256,
    "screenSize": 6.7,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 32,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2412
    },
    "image": ""
  },
  {
    "brand": "oneplus",
    "model": "OnePlus 10R 5G",
    "price": 32999,
    "rating": 86,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "dimensity",
    "numCores": 8,
    "processorSpeed": 2.85,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 80,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.7,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2412
    },
    "image": ""
  },
  {
    "brand": "vivo",
    "model": "Vivo Y22",
    "price": 14499,
    "rating": 72,
    "has5g": false,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "helio",
    "numCores": 8,
    "processorSpeed": 2.0,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 18,
    "ramCapacity": 4,
    "internalMemory": 64,
    "screenSize": 6.55,
    "refreshRate": 60,
    "numRearCameras": 2,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 8,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 720,
      "height": 1612
    },
    "image": ""
  },
  {
    "brand": "oneplus",
    "model": "OnePlus 11R",
    "price": 39999,
    "rating": 85,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 3.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 100,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.7,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2412
    },
    "image": ""
  },
  {
    "brand": "vivo",
    "model": "Vivo V25 Pro 5G",
    "price": 35999,
    "rating": 85,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "dimensity",
    "numCores": 8,
    "processorSpeed": 3.0,
    "batteryCapacity": 4830,
    "fastChargingAvailable": true,
    "fastCharging": 66,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.56,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 64,
    "primaryCameraFront": 32,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2376
    },
    "image": ""
  },
  {
    "brand": "poco",
    "model": "Poco X4 Pro 5G",
    "price": 14999,
    "rating": 80,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": true,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 67,
    "ramCapacity": 6,
    "internalMemory": 64,
    "screenSize": 6.67,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 64,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "xiaomi",
    "model": "Xiaomi Redmi Note 12",
    "price": 17859,
    "rating": 76,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": true,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.0,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 33,
    "ramCapacity": 4,
    "internalMemory": 128,
    "screenSize": 6.67,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 48,
    "primaryCameraFront": 13,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "vivo",
    "model": "Vivo V26 Pro",
    "price": 42990,
    "rating": 87,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "dimensity",
    "numCores": 8,
    "processorSpeed": 3.2,
    "batteryCapacity": 4800,
    "fastChargingAvailable": true,
    "fastCharging": 100,
    "ramCapacity": 12,
    "internalMemory": 256,
    "screenSize": 6.7,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 64,
    "primaryCameraFront": 32,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "samsung",
    "model": "Samsung Galaxy S20 FE 5G",
    "price": 31239,
    "rating": 88,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.84,
    "batteryCapacity": 4500,
    "fastChargingAvailable": true,
    "fastCharging": 0,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.5,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 12,
    "primaryCameraFront": 32,
    "extendedMemoryAvailable": true,
    "extendedUpto": 0,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
  {
    "brand": "oneplus",
    "model": "OnePlus Nord CE 2 Lite 5G (8GB RAM + 128GB)",
    "price": 21995,
    "rating": 84,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 33,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.59,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 64,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2412
    },
    "image": ""
  },
  {
    "brand": "apple",
    "model": "Apple iPhone 14 Pro Max",
    "price": 129990,
    "rating": 76,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "bionic",
    "numCores": 6,
    "processorSpeed": 0.0,
    "batteryCapacity": 4323,
    "fastChargingAvailable": true,
    "fastCharging": 0,
    "ramCapacity": 6,
    "internalMemory": 128,
    "screenSize": 6.7,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "ios",
    "primaryCameraRear": 48,
    "primaryCameraFront": 12,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1290,
      "height": 2796
    },
    "image": ""
  },
  {
    "brand": "vivo",
    "model": "Vivo V25 5G",
    "price": 27999,
    "rating": 83,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "dimensity",
    "numCores": 8,
    "processorSpeed": 2.0,
    "batteryCapacity": 4500,
    "fastChargingAvailable": true,
    "fastCharging": 44,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.44,
    "refreshRate": 90,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 64,
    "primaryCameraFront": 50,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2408
    },
    "image": ""
  },
  {
    "brand": "oneplus",
    "model": "OnePlus 11 Pro",
    "price": 69999,
    "rating": 0,
    "has5g": true,
    "hasNfc": true,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 3.2,
    "batteryCapacity": 4500,
    "fastChargingAvailable": true,
    "fastCharging": 100,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.7,
    "refreshRate": 120,
    "numRearCameras": 3,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 50,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": false,
    "extendedUpto": 0,
    "resolution": {
      "width": 1440,
      "height": 3216
    },
    "image": ""
  },
  {
    "brand": "realme",
    "model": "Realme 10 Pro (8GB RAM + 128GB)",
    "price": 19999,
    "rating": 84,
    "has5g": true,
    "hasNfc": false,
    "hasIrBlaster": false,
    "processorBrand": "snapdragon",
    "numCores": 8,
    "processorSpeed": 2.2,
    "batteryCapacity": 5000,
    "fastChargingAvailable": true,
    "fastCharging": 33,
    "ramCapacity": 8,
    "internalMemory": 128,
    "screenSize": 6.72,
    "refreshRate": 120,
    "numRearCameras": 2,
    "numFrontCameras": 1,
    "os": "android",
    "primaryCameraRear": 108,
    "primaryCameraFront": 16,
    "extendedMemoryAvailable": true,
    "extendedUpto": 1024,
    "resolution": {
      "width": 1080,
      "height": 2400
    },
    "image": ""
  },
]